### ISSUE TITLE
Add id lookup to library

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#11]
I'm still using multiple custom calls outside of trakt.py to make my script work. Would be nice to get them over to the new one.
It starts here https://github.com/Razzeee/script.trakt/blob/dev/traktapi.py#L361
* I suspect that I don't really need the summary calls, so I can probably delete them (will have to do some research)
* Rating should also be in your library, but I havent ported them yet
* So id lookup is the only real thin I'm missing
http://docs.trakt.apiary.io/#reference/search/id-lookup/get-id-lookup-results

**Comment by fuzeman** [comment]
Might have some time later today to look at this.

**Comment by Razzeee** [comment]
I just realized, if I really need don't need the summary calls, then I also don't need the lookup.

**Comment by Razzeee** [comment]
Worked out, latest dev branch is working with your wrapper only. No other trakt api code.
