### ISSUE TITLE
Use traktId for objects

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#13]
This is just a theoretical problem that bothers me.
As far as I know you are only using tvdb and imdb for the identifier tuples (for e.g. ratings)
https://github.com/Razzeee/script.trakt/blob/dev/utilities.py#L284

But we might need the trakt id as it's the only one that is always, reliably there. Other ids might be not set.

**Comment by fuzeman** [comment]
The ```pk``` field (used in the dictionary keys) will actually use the first available id, the order is:
 - **Movies:** ```imdb, tmdb, slug, trakt```
 - **Shows:** ```tvdb, tmdb, imdb, tvrage, slug, trakt```

**Note:** the "trakt" and "slug" ids were recently included in ```keys``` and the ```to_dict()``` "ids" field.

**Comment by Razzeee** [comment]
Thanks, I 've seen the commits and couldn't be happier.
