### ISSUE TITLE
Wrong logging of errors

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#14]
I'm getting errors in the logfile which should not be errors

```
17:44:20 T:5692   ERROR: [script.trakt] "POST /scrobble/stop HTTP/1.1" 201 None
```
Might be happening for all Success states other than 200?

**Comment by fuzeman** [comment]
That message is likely coming from "requests", not sure what would cause this..

**Comment by Razzeee** [comment]
Your right comes from
file _make_request  
function connectionpool 
line 362

hrm :(
