### ISSUE TITLE
Playback progress support?

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#16]
Hey Dean,

I thought you mentioned somewhere that the sync endpoint should be completely integrated, what about the progress endpoint? http://docs.trakt.apiary.io/#reference/sync/playback/get-playback-progress
If it's already there, can you give me an example call, as my suspected code did not work.

Thanks

**Comment by fuzeman** [comment]
I've got this planned in the plex plugin as well (https://github.com/trakt/Plex-Trakt-Scrobbler/issues/168), might have some time today to implement this.

**Comment by fuzeman** [comment]
Initial implementation is in the develop branch, let me know if you find any issues with it.

-------------------

```python
playback = Trakt['sync'].playback()
```

```Episode``` and ```Movie``` objects now have ```progress``` and ```paused_at``` properties

**Comment by Razzeee** [comment]
Works great for me.
Really hoping the trakt team will split the playback endpoint according to the type, as all other endpoints are. Not cool to get all when I will only use movies, but thats something for the future.

Other problem I'm having is caused by kodi itself :/
Anyway got it running with movies, works like a charm.

**Comment by Razzeee** [comment]
Types are now supported, can you change the code to support this? https://medium.com/@trakt/api-changelog-9f4041819718

**Comment by fuzeman** [comment]
They implemented that fast :smiley: (guessing you requested this change?)

I'll have a look later tonight or tomorrow, have a couple of bugs with the plex plugin that need to be fixed tonight.

**Comment by Razzeee** [comment]
Yeah, I requested it but way before I mentioned it here ;)
https://plus.google.com/+KoljaLampe/posts/7jmDtLuxZDY

**Comment by fuzeman** [comment]
This is available in the develop branch now, there does seem to be some issues with the API though..

-------------------

I'm getting some strange responses, using the ```shows``` type:
```
GET http://api-v2launch.trakt.tv/sync/playback/shows HTTP/1.1

[]
```

**Note:** there are episodes listed if you get everything with a ```GET .../sync/playback```

Thinking the API docs listed it wrong, trying ```episodes``` as the type instead just returns episodes + movies. *(this response is returned for any invalid types)*

**Comment by Razzeee** [comment]
@rectifyer @rudf0rd
can you have a look at the shows endpoint?

**Comment by rectifyer** [comment]
Yeah, this should be `episodes` and not `shows` as the filter. I just pushed the fix to staging and will push it live later today. Docs updated too.

**Comment by rectifyer** [comment]
FYI, forgot to post this update is live on the API.

**Comment by Razzeee** [comment]
Thanks! 

If I recall the commits correctly fuzeman already changed it this morning.  For the dev version.

**Comment by s7eele** [comment]
this is good news, thx for your efforts

**Comment by fuzeman** [comment]
```Trakt['sync/playback'].episodes()``` is now working correctly, thanks.

**Note:** this is only available on the develop branch currently, will likely have a new master release in the next day or two.
