### ISSUE TITLE
oAuth must be provided

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#17]
So I'm not using oAuth for kodi, but I get these messages in the log file here and there.

```
19:38:56 T:11220   DEBUG: [script.trakt] requests.packages.urllib3.connectionpool: "POST /scrobble/start HTTP/1.1" 520 None
19:38:56 T:11220 WARNING: [script.trakt] trakt.core.http: Continue retry since status is 520, waiting 5 seconds
19:39:01 T:11220 WARNING: [script.trakt] trakt.core.http: Retry # 1
19:39:01 T:11220   DEBUG: [script.trakt] requests.packages.urllib3.connectionpool: "POST /scrobble/start HTTP/1.1" 401 None
19:39:01 T:11220   DEBUG: [script.trakt] trakt.interfaces.base: response returned content-type: 'text/html', falling back to raw data
19:39:01 T:11220 WARNING: [script.trakt] trakt.interfaces.base: request failed: Unauthorized - "OAuth must be provided" (code: 401)
```

**Comment by fuzeman** [comment]
Yeah, the API docs list it as "OAuth must be provided" which is a bit confusing.

I think this is simply a generic "authentication failed" error, so this could mean a range of things:
 - invalid/missing authentication token
 - authorization revoked? (haven't tested this, just guessing)
 - token isn't for the username provided

**Comment by Razzeee** [comment]
@fuzeman 
will check the full log when I'm home. Could be possible that auth didn't return in that debugging session.

**Comment by Razzeee** [comment]
Yep, this is a follow up if the addon can't get an auth token. Nothing you can prevent, sorry for your time! :)
