### ISSUE TITLE
How to use a proxy?

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#22]
Is it already possible to use a proxy?
Like documented for requests here? 
http://docs.python-requests.org/en/latest/user/advanced/#proxies

**Comment by fuzeman** [comment]
It looks like you can just set an environment variable to enable the use of a proxy.

Something like this might work (set the environment variable before any calls to trakt.py):
```python
import os

os.environ['HTTP_PROXY'] = 'http://...'
# or
os.environ['HTTPS_PROXY'] = 'http://...'
```

---------------------------

If this doesn't work, I can just add an extra configuration parameter into trakt.py.

**Comment by Razzeee** [comment]
Can you please have a look if I missed something?
https://github.com/Razzeee/script.trakt/commit/3eab97a11bf3e171a3b1fc17f5908a7e834518fa
https://github.com/Razzeee/script.trakt/issues/181#issuecomment-98806541

**Comment by fuzeman** [comment]
Looks like the environment variables don't work with ```requests.Session```, try this instead (update to the **develop** branch of trakt.py):
```python
Trakt.http.proxies = {
    'http': 'http://<username>:<password>@<host>:<port>',
    'https': 'http://<username>:<password>@<host>:<port>'
}
```

**Note:** the ```proxies``` dictionary maps specific request schemes to a proxy, set both "http" and "https" to the same proxy url.

**Comment by Razzeee** [comment]
I'm not sure I understand you? Should there be a new commit to the develop branch?

Should this stay like this or do I use the real url? Should both be http or can both also be https?
```
Trakt.http.proxies = {
    'http': 'http://<username>:<password>@<host>:<port>',
    'https': 'http://<username>:<password>@<host>:<port>'
}
```

**Comment by fuzeman** [comment]
Woops, only pushed the commit to my private git server. https://github.com/fuzeman/trakt.py/commit/fedd568a3a7ce33ffc5ea2377ae671a08ee35936 adds the "proxies" attribute.

You should be able to just replace:
```python
        proxyURL = checkAndConfigureProxy()
        if proxyURL:
            if proxyURL.startswith('http://'):
                os.environ['HTTP_PROXY'] = proxyURL
            elif proxyURL.startswith('https://'):
                os.environ['HTTPS_PROXY'] = proxyURL
```

with (untested, make sure the indentation is correct):
```python
        proxyURL = checkAndConfigureProxy()
        if proxyURL:
            Trakt.http.proxies = {
                'http': proxyURL,
                'https': proxyURL
            }
```

**Comment by Razzeee** [comment]
Working flawless, thank you!
