### ISSUE TITLE
Implement user  settings endpoint

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#24]
Would it be possible to get an implementation of https://api-v2launch.trakt.tv/users/settings
or more suited for me https://api-v2launch.trakt.tv/me/settings

I find it very confusing at the moment, that you enter your pin in the settings but might forget from which user this is. So I would like to display that, basically just the name. Because as far as I know the auth process doesn't return the username.

**Comment by fuzeman** [comment]
```Trakt['users/settings'].get()``` already exists *([trakt/interfaces/users/settings.py](https://github.com/fuzeman/trakt.py/blob/master/trakt/interfaces/users/settings.py))*, this returns the settings for the currently authenticated user.
