### ISSUE TITLE
SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#25]
There seems to be a problem for some clients with the SSL certificate.
See this log: http://xbmclogs.com/pjkndtvww#line-1599

This seems to be a solution, but only you will know for sure
https://lukasa.co.uk/2013/01/Choosing_SSL_Version_In_Requests/
http://stackoverflow.com/a/14146031/2859813

**Comment by fuzeman** [comment]
The trakt API (CloudFlare) does only support TLSv1, so forcing requests to use TLSv1 connections might fix this error.

I'll try have this fix implemented later today.

**Comment by fuzeman** [comment]
Just pushed the fix to the develop branch, let me know if you find any issues with it.

**Comment by Razzeee** [comment]
Well doesn't seem to change any dates for my sync, so we should be fine.
