### ISSUE TITLE
Insecure platform warning

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#27]
Any chance, to get this fixed? Or do I need to do something to the requests package?

```22:47:12 T:11192   ERROR: C:\Users\razze\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.```

**Comment by fuzeman** [comment]
Sounds like you need to update python or use PyOpenSSL ([source](https://urllib3.readthedocs.org/en/latest/security.html#pyopenssl)), probably more an issue for the Kodi team to fix.

**Comment by Razzeee** [comment]
Thought that might be the case, thank you
