### ISSUE TITLE
Grabbing error codes?

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#4]
Hey everybody,

is there a way we can get the error from the library? As far as I've seen it only adds it to the logfile, no luck with try etc.

Cheers

**Comment by fuzeman** [comment]
I've started adding an ```exceptions=True``` parameter (in the develop branch) to enable exceptions on request failures, this means you can catch ```trakt.RequestError``` to retrieve the error code and raw response.

**Comment by Razzeee** [comment]
@fuzeman 
Will have a look tomorrow, thank you!

**Comment by Razzeee** [comment]
Could you write a small example? I'm new to python, would be appreciated. I probably have to import the error interface? Would be nice to use the same errors for my calls to the other trakt endpoints.

**Comment by fuzeman** [comment]
```python
from trakt import Trakt, ClientError, ServerError
import logging
import os

# Configure
logging.basicConfig(level=logging.DEBUG)

Trakt.configuration.defaults.client(
    id=os.environ.get('CLIENT_ID')
)


try:
    token = Trakt['auth'].login(
        os.environ.get('USERNAME'),
        os.environ.get('PASSWORD'),
        exceptions=True
    )

    print 'Authentication token: %r' % token
except ClientError, ex:
    # Client error (status_code < 500 - invalid username or password, etc..)
    print ex.status_code, ex.error
except ServerError, ex:
    # Server error (status_code >= 500)
    print ex.status_code, ex.error
except Exception, ex:
    # Connection error (SSL handshake failure, timeout, etc..)
    print ex

```

```ex.error``` returns a ```(<name>, <description>)``` tuple roughly explaining the status code from these choices: https://github.com/fuzeman/trakt.py/blob/develop/trakt/core/errors.py

```ex.response``` is also available to inspect the actual ```Response``` returned from the python [requests](http://docs.python-requests.org/en/latest/) library

**Comment by Razzeee** [comment]
@fuzeman 
can you think of any way that I could centrally wrap an trakt api call in python and call it dynamically?
So for this for e.g. I would have to pass in 'auth', login and the username and password
´´´
Trakt['auth'].login(
        os.environ.get('USERNAME'),
        os.environ.get('PASSWORD'),
        exceptions=True
    )
´´´
