### ISSUE TITLE
transparent trakt call

### ISSUE THREAD

**Issue by GreenAir** [fuzeman/trakt.py#43]
could you add a possibility for transparent trakt calls for functions that are not supported?
e.g. collection=Trakt['shows/'+showID+'/progress/collection']

maybe it is already possible but your interface-machine is too complicated for me to understand properly! :-/

**Comment by fuzeman** [comment]
Shouldn't be too hard to implement, will have a look later this week.

**Comment by fuzeman** [comment]
Using the normal syntax (```Trakt[<interface>].<method>()```) for unsupported interfaces/methods was going to be quite difficult to support.

I've decided to just make some changes so the HTTP client can be called directly (available on the "develop" branch now), for example:
```python
response = Trakt.http.get('/shows/tt0944947/progress/collection', authenticated=True)
data = response.json()
```

**Comment by fuzeman** [comment]
Release in v2.5.2
