### ISSUE TITLE
Getting all episodes of a show

### ISSUE THREAD

**Issue by ineffablebob** [fuzeman/trakt.py#47]
I see in the trakt API that you can do a lookup for all episodes of a show using the "seasons" method if you include "?extended=episodes" in the URL.

http://docs.trakt.apiary.io/#reference/seasons/summary/get-all-seasons-for-a-show

I've looked in the code here but I wasn't able to find a way to make this happen. Is there an option to one of the methods that would allow this to happen? If not, can it be added?

**Comment by fuzeman** [comment]
> Is there an option to one of the methods that would allow this to happen? If not, can it be added?

This isn't supported currently, I'll try have it implemented later this week.

**Comment by ineffablebob** [comment]
Thanks, appreciate it!

**Comment by fuzeman** [comment]
The "develop" branch now supports this:
```python
Trakt['shows'].seasons('<id>', extended='episodes')
```

Let me know if you find any issues :smile:

**Comment by ineffablebob** [comment]
Updated my copy of the code with the develop branch, tried it out, had no problems. Looks good to me, thanks!

**Comment by fuzeman** [comment]
Released in [v2.6.0](https://github.com/fuzeman/trakt.py/releases/tag/2.6.0)
