### ISSUE TITLE
Contact email

### ISSUE THREAD

**Issue by ofek** [fuzeman/trakt.py#55]
I was wondering if me@dgardiner.net in `setup.py` is still a way to contact you. Going to [dgardiner.net](http://dgardiner.net) leads to a page that makes it appear to have been expired/taken.

**Comment by fuzeman** [comment]
Yeah, that's still my email address. Just have no website at dgardiner.net yet, should probably redirect it to my GitHub profile to avoid any confusion with the "parked" page.

**Comment by ofek** [comment]
Oh ok great! I just sent you an email :)

**Comment by ofek** [comment]
You can close this, but did you receive my email?

**Comment by fuzeman** [comment]
Just replied :smiley:
