### ISSUE TITLE
watched attribute always None in Episode

### ISSUE THREAD

**Issue by Notmarrco** [fuzeman/trakt.py#59]
Hi,

I want to know if a given episode has already been watched. Even with extended='full', the Episode.is_watched is always None or 0 (but I can confirm that the episode is marked as watched in the trakt web interface).

I tried with both ```Trakt['search'].lookup(trakt_id, service='trakt', extended='full')``` and ```Trakt['shows'].episode(slug, seasonnumber, episodenumber, extended='full')```

Am I doing something wrong there ?

thanks

**Comment by sharkykh** [comment]
@Notmarrco 	
As far as I know, the Trakt API does not provide the watched / collected statuses when calling other endpoints like search, shows, movies, lists, etc.
You are required to call [`sync/watched`](https://trakt.docs.apiary.io/#reference/sync/get-watched/get-watched) if you want to know the watched status ([or collection status](https://trakt.docs.apiary.io/#reference/sync/get-collection/get-collection)), and then you can join the data with the data from the other endpoints.
Hope that helps.

**Comment by Notmarrco** [comment]
Thanks.

Fwiw since then I used : `/users/{user}/history/{media_type}/{trakt_id}` that can also return the watched status.
