### ISSUE TITLE
Exceptions=true breaking retries?

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#7]
I could be wrong, but it seems like there is a case when retries are not working correctly. Might be when exceptions are thrown.

**Comment by fuzeman** [comment]
Currently retries only happen when the API returns a response with a 5xx error code, if a response was never returned (server timeout, ssl error, etc..) it will just raise an exception.

Could this be what you are seeing?

**Comment by Razzeee** [comment]
hrm, I would have thought especially timeouts would be a prime suspect that we want to retry

**Comment by fuzeman** [comment]
I thought timeout errors were retried internally by urllib3/requests anyway, turns out this isn't enabled by default...

I'll enable this in the plugin later today.

**Comment by fuzeman** [comment]
urllib3/requests now retries requests on connection errors (default: 3 retries), this can only be changed if you create a new client instance like this:
```python
from trakt import TraktClient

client = TraktClient(adapter_kwargs={'max_retries': 2})

token = client['auth'].login(...)
```

Added at https://github.com/fuzeman/trakt.py/commit/c6b1777be3dc5caddb48bc597eb87a842bc079d5
