### ISSUE TITLE
Add extended info for user list items

### ISSUE THREAD

**Issue by mza921** [fuzeman/trakt.py#70]
Looks like the Trakt.tv API spec allows for extended info for list items: [https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-custom-list](url)

I imagine this is a similar enhancement to #57

**Comment by fuzeman** [comment]
Released in [v3.2.0](https://github.com/fuzeman/trakt.py/releases/tag/3.2.0), thanks for the pull request.
