### ISSUE TITLE
Limit results from trending movies requests

### ISSUE THREAD

**Issue by mza921** [fuzeman/trakt.py#72]
It looks like `Trakt['movies'].trending()` will only return the first page of 10 results or all results with the `pagination=True` argument. Could you add the ability to return a specific number of results? Or at least implement `page` and `limit` arguments as described in [https://trakt.docs.apiary.io/#introduction/pagination](url)

**Comment by fuzeman** [comment]
I've redesigned the pagination system in https://github.com/fuzeman/trakt.py/commit/cd971db3b0bd0e8c2fd73d95e10b6c5ff7354f13. This commit adds `page` and `per_page` parameters to supported functions and has some improvements to `pagination=True` to support retrieving specific pages.

I'll try have this included in a new release later this week.

**Comment by fuzeman** [comment]
Released in [v4.0.0](https://github.com/fuzeman/trakt.py/releases/tag/4.0.0)
