### ISSUE TITLE
Continue previous session

### ISSUE THREAD

**Issue by SonOfDiablo** [fuzeman/trakt.py#73]
Hello,

Is it possible to continue from a previously authorized session?

I'm currently doing an oauth authentication, but I can't really figure out how I would save and reuse the token the next time I run my script so I don't have to go through the whole auth process again.

Is this even possible with this library?

**Comment by OptimusGREEN** [comment]
I'd also like to know this as its not clear in the readme.

**Comment by SonOfDiablo** [comment]
I just dropped the library and started using the api directly instead, since I didn't get an answer.

**Comment by fuzeman** [comment]
**Authentication Flow:**

1. Generate an authorization url:
    ```python
    url = Trakt['oauth/pin'].url()
    ```
2. Navigate to the URL to receive a pin
3. Exchange the pin code for a token (which is valid for 3 months)
    ```python
    token = Trakt['oauth'].token_exchange(pin, 'urn:ietf:wg:oauth:2.0:oob')
    ```
4. Authenticated requests can now be sent with:
    ```python
    with Trakt.configuration.oauth.from_response(token):
        print(Trakt['sync/collection'].movies())
    ```

**Save / Restore:**

The `token` received in step 3 should be encoded (e.g. JSON) and saved to disk. This token can be decoded and used again for authenticated requests (same as in step 4) without requesting another pin from the user.

**Token Refresh**

If you are wanting to use the token for a period longer than 3 months, you also need to update the stored token when a refresh event is fired.

Example:
```python
def on_token_refreshed(token):
    ... write `token` to disk...

Trakt.on('oauth.token_refreshed', on_token_refreshed)
```

------------

The examples in [examples/authentication](https://github.com/fuzeman/trakt.py/tree/master/examples/authentication) may also provide a bit more detail.
