### ISSUE TITLE
Support querying for user list items by type

### ISSUE THREAD

**Issue by mza921** [fuzeman/trakt.py#75]
Trakt.tv API spec allows for an optional `type` parameter for list items: 
[https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-custom-list](https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-custom-list) 
 
This allows for something like, 
`Trakt['users/me/lists/mylist'].items(item_type='movie')` 
-or- 
`Trakt['users/me/lists/mylist'].items(item_type='show')` 
to return only the requested type of item.

**Comment by fuzeman** [comment]
I've merged #76 which will be included in the next release.
