### ISSUE TITLE
Implement lists/trending and lists/popular 

### ISSUE THREAD

**Issue by milokmet** [fuzeman/trakt.py#80]
Hello, thanks for merging and improving my previous commits.

I almost forgot about these useful methods that I used in my kodi plugin - to allow user to browse through trending and popular lists.

The usage sholud be like
Trakt['lists'].popular()
Trakt['lists'].trending()

I tried to implement it, but I cannot figure out, how to attach user to List object, because I lost in some circular import of UserMapper in List class.

Another issue with List is that interface Users
Trakt['users'].likes('lists') is returning CustomLists, but lists in users/*/like are "public" lists. The returned CustomList contains only "username" field but to retrieve the lists it is necessary to use users's slug id and also List id/slug. And I think it is not a good idea to have .add delete methods on lists that do not belong to the current authenticated user. And actions like likelist or unlike should be available on List rather than CusomList.

Thanks

**Comment by milokmet** [comment]
Can it be implemented like this? https://github.com/milokmet/trakt.py/commit/2a9109e25060829e6bce529214a6ad80ad88259d

**Comment by fuzeman** [comment]
I've gone ahead and implemented this on the `develop` branch. Let me know if you spot any problems with it.

**Comment by milokmet** [comment]
Hi, it seems everything is working fine. Thank you!
