### ISSUE TITLE
Regression in version 4.x

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#83]
Hey there, 

haven't really had the time to look into it, but thought I would quickly open up an issue to let you know.

There seems to be some problem https://github.com/trakt/script.trakt/issues/503#issuecomment-640223684

Not sure if that just a problem with constructing the movie ratings api endpoint or if more is affected.

https://forum.kodi.tv/showthread.php?tid=220547&pid=2955335#pid2955335

**Comment by Razzeee** [comment]
My hunch would be that I need to use the store param now? As you do in https://github.com/fuzeman/trakt.py/commit/fc59c50ca5c8d290d9896c4f188182ff741afee0 but not in the examples https://github.com/fuzeman/trakt.py/blob/master/examples/collection.py#L45

I also can't find it referenced in the changelog.

So this and a bunch of other calls need changing? https://github.com/trakt/script.trakt/blob/master/resources/lib/traktapi.py#L225

**Comment by fuzeman** [comment]
Apologies, these changes should have been described in the change log. Using `store=` is recommended moving forward to allow more common parameters to be defined at the front (e.g. `id`, `start_at`, `end_at`, `rating`, `sort`).

I would be careful when upgrading across major releases as they will always contain some breaking changes. Users should pin to a specific version with `trakt.py==4.1.0` or major with `trakt.py~=4.0` to avoid updates that may break functionality in their application.

It appears Kodi doesn't support maximum version specifiers. In this case maybe a new module should be created for each trakt.py major release (e.g. `script.module.trakt4`) to avoid unexpected errors in plugins?

**Comment by Razzeee** [comment]
I guess recommended means mandatory :)

Yes, kodi can't pin and your probably correct, about having different versions like that, but I didn't spot anything serious in the changelog and thought we're good to upgrade.

**Comment by fuzeman** [comment]
> I guess recommended means mandatory :)

Using `Trakt['sync/ratings'].movies(None, store)` is also possible but would stop working if another parameter is added in a future update.

**Comment by Razzeee** [comment]
I'm correct, that only `Trakt['sync/ratings'].movies`, `Trakt['sync/ratings'].episodes`, `Trakt['sync/ratings'].shows`, `Trakt['sync/ratings'].seasons` is affected?

**Comment by fuzeman** [comment]
Full list is:
 - `Trakt['sync/history']` `get()`, `movies()`, `shows()`
 - `Trakt['sync/ratings']` `get()`, `movies()`, `shows()`, `seasons()`, `episodes()`
 - `Trakt['sync/watchlist']` `get()`, `movies()`, `shows()`, `seasons()`, `episodes()`
