### ISSUE TITLE
Issues with Trakt

### ISSUE THREAD

**Issue by ThatSlimGuy** [fuzeman/trakt.py#84]
Can't seem to figured out what's going on, has put me through hell and back trying to work out what the issues are, had to delete me entire data base and start fresh thinking it would fix it but still having issues.

Can't get the addon to work at the end of any show or movie, won't let me rate an item, will only pop up and allow Kodi to mark as watched when going to the very end of the file. 

Talked with Razee and he believes the issue is with this side of things. Is there something going on with the plugin right now ??

**Comment by ThatSlimGuy** [comment]
Here is my log, i think i see where the error happens on line 3348

 https://paste.kodi.tv/nuyucujuva.kodi

**Comment by Razzeee** [comment]
https://github.com/trakt/script.trakt/issues/504

**Comment by fuzeman** [comment]
It looks like this might be related to connection pooling in requests/urllib3, the log file shows the request is made without any re-connection attempt (which would be expected after 20 minutes of no requests to Trakt.tv).

The log file does show earlier requests trigger re-connections:
```
18:12:06.375 T:175723484400   DEBUG: [script.trakt] urllib3.connectionpool: Starting new HTTPS connection (1): api.trakt.tv:443
```
```
18:33:20.296 T:175723484400   DEBUG: [script.trakt] urllib3.connectionpool: Resetting dropped connection: api.trakt.tv
```

I'm guessing requests/urllib3 is failing to retry requests on dropped connections for some reason, no idea what would be causing this...

----------

@Razzeee Duplicate scrobbles are rejected by Trakt.tv now ([source](https://support.trakt.tv/forums/188762-general/suggestions/36386326-reject-duplicate-plays-to-history)), so you could try enable `retry=True` for `Trakt['scrobble'].stop` at [traktapi.py#L160](https://github.com/trakt/script.trakt/blob/e80565a475ff175dc6c85a04f07d3c5da60bcc83/resources/lib/traktapi.py#L160). This could be added as a separate configuration option to avoid any risk of duplication for existing users.

**Comment by ThatSlimGuy** [comment]
This pretty much happens every time without fail when playing things through kodi on 2 seperate machines, 2 seperate versions with a variations in versions on each other them. Which kept pushing me to believe it was something to do with my trakt. But, even using a fresh account from trakt, same issue occurred each and every time!

Ive not resorted to just watching what ever things i watch. And at some point either update library, which in turn runs trakt at the end. Or set a shortcut for trakt to run at the bottom of a skin to then force mark stuff as watched there. I watced a total of about 8-10 episodes in the last 2 days. Ratings never popped in any of them. Most episodes have about a minute left when i end them, and have gone well past the % time i had set on them for it to initiate. Very confusing.

**Comment by ThatSlimGuy** [comment]
Can I just leave a final note if this is being closed, more so if anyone else ever comes across this exact same issue. It was never solved or fixed. Still have same issues even as recent ad yesterday. Not sure why, looks as if I never will. Thanks for the assistance either way.

**Comment by fuzeman** [comment]
I detailed a possible workaround that could be implemented in script.trakt. Decided to close this issue as there was nothing more planned in trakt.py in relation to this issue.

**Comment by ThatSlimGuy** [comment]
> I detailed a possible workaround that could be implemented in script.trakt. Decided to close this issue as there was nothing more planned in trakt.py in relation to this issue.

Yeah that's cool. Nothing got changed so not much else I can do. I can't possibly be the only person out there that has the issue, but I've learned to live with it now. Againni do appreciate the help!

**Comment by Razzeee** [comment]
https://github.com/trakt/script.trakt/commit/e415f9f9cb8f9e8d1d9322b9002561c526d0a34e has been added and released for matrix, we could backport that, but only if it's confirmed, that it helps.

**Comment by ThatSlimGuy** [comment]
I guess I could always just tried matrix on my Nvidia shield. Either way if it can be added to an older version with out to much hassle I'm happy to test it to see if it works. I'm only going by what you guys have said based upon my log file. Is it easier for me to test a version of matrix ?

**Comment by Razzeee** [comment]
I'm quiet short on time, so that's my problem right now.
