### ISSUE TITLE
Add support for Popular/Recommended Movies/Shows

### ISSUE THREAD

**Issue by mza921** [fuzeman/trakt.py#87]
Add support for 
- [Popular movies](https://trakt.docs.apiary.io/#reference/movies/popular/get-popular-movies)
- [Recommend movies](https://trakt.docs.apiary.io/#reference/movies/recommended)
- [Popular shows](https://trakt.docs.apiary.io/#reference/shows/popular/get-popular-shows)
- [Recommend shows](https://trakt.docs.apiary.io/#reference/shows/recommended)

Probably similar to `.trending()` support added in 4.2.0.

**Comment by meisnate12** [comment]
i think it already has support for popular 

https://github.com/fuzeman/trakt.py/blob/master/trakt/interfaces/lists/__init__.py
at Line 14

**Comment by mza921** [comment]
No, that returns a list of Lists.

**Comment by meisnate12** [comment]
ahh i just saw the trending there and figured it was the same thing but for popular

**Comment by fuzeman** [comment]
`popular()` was released in [v4.3.0](https://github.com/fuzeman/trakt.py/releases/tag/4.3.0), and `recommended()` was released in [v4.4.0](https://github.com/fuzeman/trakt.py/releases/tag/4.4.0)
