### ISSUE TITLE
ReadTimeout Error

### ISSUE THREAD

**Issue by spilote** [fuzeman/trakt.py#88]
from trakt import Trakt
/usr/local/lib/python2.7/dist-packages/arrow/arrow.py:28: DeprecationWarning: Arrow will drop support for Python 2.7 and 3.5 in the upcoming v1.0.0 release. Please upgrade to Python 3.6+ to continue receiving updates for Arrow.
  DeprecationWarning,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/trakt/__init__.py", line 3, in <module>
    from trakt.client import TraktClient
  File "/usr/local/lib/python2.7/dist-packages/trakt/client.py", line 5, in <module>
    from trakt.core.http import HttpClient
  File "/usr/local/lib/python2.7/dist-packages/trakt/core/http.py", line 13, in <module>
    from requests.packages.urllib3.exceptions import ReadTimeoutError
ImportError: cannot import name ReadTimeoutError

What am I missing here???

thanks!!

**Comment by fuzeman** [comment]
It looks like requests v2.16.0+ has a breaking change that is incompatible with trakt.py. I'll include a fix in the next release.

**Comment by fuzeman** [comment]
It appears this issue was fixed in requests v2.16.1, so updating requests to anything later than v2.16.0 should resolve this issue.

I've also updated the trakt.py requirements to mark v2.16.0 as not supported. This will be included in the next release.

**Comment by fuzeman** [comment]
Released in [v4.3.0](https://github.com/fuzeman/trakt.py/releases/tag/4.3.0)
