### ISSUE TITLE
"Images" is None when using extended=full

### ISSUE THREAD

**Issue by Archmonger** [fuzeman/trakt.py#89]
Been testing out trakt.py and came across this scenario.
```python
Trakt.configuration.defaults.app(id="xxxx")
Trakt.configuration.defaults.client(
    id="xxxx",
    secret="xxxx",
)

for show in Trakt["movies"].trending(extended="full"):
    pprint(vars(show))
```

Seems like `images` is always populated with `None` on this endpoint. Is this expected?

**Comment by fuzeman** [comment]
Images were removed from the Trakt API in 2016 (https://apiblog.trakt.tv/trakt-api-images-56b43c356427).

See https://trakt.docs.apiary.io/#introduction/images for details on the availability of images from other APIs.
