### ISSUE TITLE
Update requirements?

### ISSUE THREAD

**Issue by Razzeee** [fuzeman/trakt.py#91]
Can requirements be updated? I'm wondering if a recent arrow version would be good for e.g.

See https://github.com/arrow-py/arrow/issues/738#issuecomment-794456222

**Comment by fuzeman** [comment]
It looks like trakt.py is compatible with arrow v1.0.0+ (based on https://github.com/arrow-py/arrow/issues/832), so the arrow version range in `requirements.txt` can be expanded easily. I'll include this in the next release.

**Comment by fuzeman** [comment]
Released in [v4.3.0](https://github.com/fuzeman/trakt.py/releases/tag/4.3.0)
